### ISSUE TITLE
Add definition for REST API search results

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/wp-json-schemas#16]
* `/wp/v2/search`

**Comment by kevinwhoffman** [comment]
@johnbillion I've begun working on a PR to add schemas for search results from the `/wp/v2/search` endpoint. I'm following the contributing guidelines and referencing the existing schemas for comparison. I noticed that other endpoints have schemas for both plural (e.g. `WP_REST_API_Posts`) and singular (e.g. `WP_REST_API_Post`) forms of the returned items.

I am wondering if my PR should include include both `WP_REST_API_Search_Results` and `WP_REST_API_Search_Result` or just one and not the other?

**Comment by johnbillion** [comment]
Great! Thanks very much.

The plural schemas represent the complete response, which is an array of the singular schemas. You don't need to worry about the plural schema for now, it can be added once the singular schema is finished.

Let me know if you have any more questions.

**Comment by johnbillion** [comment]
I just realised the documentation isn't entirely clear because it doesn't state that `WP_REST_API_Posts` is an array of `WP_REST_API_Post` objects. I'll clarify that.

For REST API search results there should still be a singular schema that makes up the collection schema even though there's no concept of querying for a single search result.
