### ISSUE TITLE
Namespaced Schemas per Context

### ISSUE THREAD

**Issue by dkress59** [johnbillion/wp-json-schemas#48]
Hi there :wave: 
thanks for setting up this package, I've extensively been working with wp-types. In fact, I'm currently finishing up a proper typescript [wordpress-api-client](https://github.com/dkress59/wordpress-api-client), which builds upon wp-types.

So far it has been a blessing, but I have **the issue** that the typings sometimes are not 100% accurate (relates to #33):
Typings of REST responses include fields of all contexts as optional parameters – even if a response in the "view" context definitely does not contain certain fields of the "edit" context, **the typings of responses in both contexts are the same** – the context-specific fields are simply typed as optional, for both.

I will add an example to better illustrate the problem.

_on a side note:_ I'm not going to open another issue for this, it's just a question: are you planning on including wp-api request DTOs, as well?

:fist_raised: keep it up

**Comment by dkress59** [comment]
Here's an example, in the embed context there is no "content" field (wp default).

### Context: Embed

https://techcrunch.com/wp-json/wp/v2/posts/2258167/?context=embed

### Context: View

https://techcrunch.com/wp-json/wp/v2/posts/2258167/?context=view

I propose something along the lines of

```typescript
namespace WP_REST_API
    namespace EDIT {
        export interface Post {
            // ...
        }
        // ...
    }
    namespace EMBED {
        export interface Post {
            // ...
        }
        // ...
    }
    namespace VIEW {
        export interface Post {
            // ...
        }
        // ...
    }
}

**Comment by johnbillion** [comment]
Yeah I came to the same realisation myself in #40. I haven't made any plans to tackle it though.

**Comment by dkress59** [comment]
Ah, I see, so this is basically a duplicate of #40.Sorry,  I'll close this.
Thanks for getting back so quickly :v:
