### ISSUE TITLE
`mime_type` / `media_type` incorrect/missing for `WP_REST_API_Attachment`

### ISSUE THREAD

**Issue by swissspidy** [johnbillion/wp-json-schemas#52]
When fetching attachments or uploading a file via `wp/v2/media`,there are two similar fields in the schema: `mime_type` and `media_type`.

`mime_type` is the mime type
`media_type` is either `image` if it's an image, or `file` if it's something else (not really useful, but alas)

https://github.com/WordPress/wordpress-develop/blob/5ce8b1f9ed99004c73771ad00adc249c2b293a70/src/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php#L756-L762

https://github.com/WordPress/wordpress-develop/blob/5ce8b1f9ed99004c73771ad00adc249c2b293a70/src/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php#L915-L928

The schema here somehow mixes the two together and thinks that `media_type` is the mime type, and `mime_type` does not exist:

https://github.com/johnbillion/wp-json-schemas/blob/e638e71df6e04fddb2dad3548b9549e031389dd8/schemas/rest-api/attachment.json#L172-L176

**Comment by johnbillion** [comment]
Thanks! I see that `mime_type` is present in the `required` list but it doesn't have a definition in `properties`. I'll see if I can add a test to cover this.

**Comment by johnbillion** [comment]
@swissspidy I added tests for this schema and it exposed a couple of other minor issues. All fixed in 3.62.1. Thanks for the report!
